# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'UIBezierPath Demo' do

pod 'Mantle', '~> 2.0.7'

end

target 'UIBezierPath DemoTests' do

end

target 'UIBezierPath DemoUITests' do

end

